export const roles = {
  admin: {
    name: 'Admin',
    description: 'Full access to all features',
    permissions: [
      'questions.create',
      'questions.read',
      'questions.update',
      'questions.delete',
      'questions.upload',
      'rounds.create',
      'rounds.read',
      'rounds.update',
      'rounds.delete',
      'games.create',
      'games.read',
      'games.update',
      'games.delete',
      'games.play',
      'users.create',
      'users.read',
      'users.update',
      'users.delete',
      'dashboard.view',
      'dashboard.stats',
      'dashboard.activity',
    ],
  },
  teacher: {
    name: 'Teacher',
    description: 'Can manage questions, rounds, and games',
    permissions: [
      'questions.create',
      'questions.read',
      'questions.update',
      'questions.delete',
      'questions.upload',
      'rounds.read',
      'games.create',
      'games.read',
      'games.update',
      'games.delete',
      'dashboard.view',
      'dashboard.stats',
      'dashboard.activity',
    ],
  },
  player: {
    name: 'Player',
    description: 'Can view and play games',
    permissions: [
      'questions.read',
      'rounds.read',
      'games.read',
      'games.play',
      'dashboard.view',
    ],
  },
};
